### ISSUE TITLE
ModuleNotFoundError: No module named 'unagi.unagi'

### ISSUE THREAD

**Issue by jimz7** [HazyResearch/thanos-code#1]
Hello, I'm trying to test out whether I correctly setup the repo. I have installed the required modules, including unagi, but I still always get the ModuleNotFoundError: No module named 'unagi.unagi' when I run 'unagi +experiment=test dataflow.data_dir=LOCAL_PATH_TO_DOWNLOAD_CIFAR'

How can I solve it?

**Comment by DanFu09** [comment]
Hi, thank you for your interest!

This looks like an install error - can you list all the steps/commands you used to install it?

**Comment by jimz7** [comment]
Hello Dan, I used the command that you posted:
`git clone https://github.com/HazyResearch/thanos-code.git`
`cd thanos-code`
`export PATH="<path to conda dir>/anaconda3/bin:$PATH"`, where I replaced `path to conda dir` as the path where I installed miniconda.
`conda create -n unagi_env python=3.8`
`conda activate unagi_env`
`make dev`

**Comment by DanFu09** [comment]
Did the install succeed? If you run Python from within `unagi_env` can you `import unagi`?

**Comment by zjz123-eng** [comment]
> Did the install succeed? If you run Python from within `unagi_env` can you `import unagi`?

Hello Dan. I can `import unagi` under `unagi_env`, but the weird things is that there's no module named `unagi.unagi` even after download.
`  File "/home/jz24694/miniconda3/bin/unagi", line 9, in <module>
    from unagi.unagi import main as unagi_main
ModuleNotFoundError: No module named 'unagi.unagi'
`

**Comment by DanFu09** [comment]
From within the `unagi_env` can you run these commands in Python and paste the output:
```
import unagi
print(unagi.__file__)
import unagi.unagi
from unagi.unagi import main
```

**Comment by zjz123-eng** [comment]
My output is the following:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import unagi
>>> print(unagi.__file__)
/home/jz24694/miniconda3/envs/unagi_env/lib/python3.8/site-packages/unagi/__init__.py
>>> import unagi.unagi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unagi.unagi'
>>> from unagi.unagi import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unagi.unagi'
```
Thanks for replying!

**Comment by DanFu09** [comment]
This is what I see when I run these commands:
```
>>> import unagi
>>> print(unagi.__file__)
None
>>> print (unagi.unagi.__file__)
/PATH_TO_THANOS_CODE/thanos-code/unagi/unagi.py
```

Do you have another package installed called `unagi`? There may be a namespace conflict (note that there is not an init file in the folder: https://github.com/HazyResearch/thanos-code/tree/main/unagi).

**Comment by zjz123-eng** [comment]
Hello, I re-installed everything again, and now this is my output of running these commands under `thanos-code` folder:
```
>>> import unagi
>>> print(unagi.__file__)
None
>>> print(unagi.unagi.__file__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'unagi' has no attribute 'unagi'
>>>

```
Also, I get the following output when running `unagi +experiment=test dataflow.data_dir=LOCAL_PATH_TO_DOWNLOAD_CIFAR`
![image](https://user-images.githubusercontent.com/37298719/173004219-1c10149d-b9fb-4a9d-ba02-87422a685ec8.png)
![image](https://user-images.githubusercontent.com/37298719/173004162-2f2c38d5-e622-4689-84dc-4dab0a9ce067.png)

**Comment by DanFu09** [comment]
That is the expected behavior. The test script only runs for a few epochs.

**Comment by zjz123-eng** [comment]
Thanks! Now I can do training. One extra question: If I have multiple GPUs, how can I assign one of them to do training?
